### ISSUE TITLE
Can't make new repository

### ISSUE THREAD

**Issue by efvicario** [ds4owd-001/md-03-assignments-efvicario#2]
Hi there @larnsce @mianzg @sskorik01,

I made the spreadsheet but can't create a new repository under the course page (only under my personal username). The green "New" button doesn't appear for me when I scroll down to repositories. I've followed the steps making a personal repository but I'm guessing we will use the spreadsheet in class today and need to push changes?

Elizabeth

**Comment by sskorik01** [comment]
Hi Elizabeth, 

What about if you click on the "Repositories" tab? Do you see the "New repository" button there? Let me know

**Comment by efvicario** [comment]
Hi, 
No, there is no button to create one. I see the search bar, then "type," "language," and "sort" buttons. I can use the plus sign in the top right, but that only creates one with me as the owner.
Elizabeth

**Comment by sskorik01** [comment]
Hi Elizabeth,
You probably didn't get an invitation to be member of the organization, so you were considered as an external member. I just sent you an invitation, let me know if it works!
Best, 
Sophia

**Comment by efvicario** [comment]
Hi Sophia,
Yes, this resolved my issue! Thanks so much.
Elizabeth
